/* Automatically generated by wasm2c */
#ifndef MODULE_H_GENERATED_
#define MODULE_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;

typedef struct w2c_Module {
  struct w2c_env* w2c_env_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_Module;

void wasm2c_Module_instantiate(w2c_Module*, struct w2c_env*);
void wasm2c_Module_free(w2c_Module*);
wasm_rt_func_type_t wasm2c_Module_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'ImGuiBegin' */
void w2c_env_ImGuiBegin(struct w2c_env*, u32);

/* import: 'env' 'ImGuiEnd' */
void w2c_env_ImGuiEnd(struct w2c_env*);

/* import: 'env' 'ImGuiText' */
void w2c_env_ImGuiText(struct w2c_env*, u32);

/* import: 'env' 'addArgNull' */
void w2c_env_addArgNull(struct w2c_env*);

/* import: 'env' 'addArgObject' */
void w2c_env_addArgObject(struct w2c_env*, u32);

/* import: 'env' 'call' */
u32 w2c_env_call(struct w2c_env*, u32, u32);

/* import: 'env' 'clearArgs' */
void w2c_env_clearArgs(struct w2c_env*);

/* import: 'env' 'dropObject' */
void w2c_env_dropObject(struct w2c_env*, u32);

/* import: 'env' 'getArgCount' */
u32 w2c_env_getArgCount(struct w2c_env*);

/* import: 'env' 'getMethodByIdentifier' */
u32 w2c_env_getMethodByIdentifier(struct w2c_env*, u32);

/* import: 'env' 'getOriginal' */
u32 w2c_env_getOriginal(struct w2c_env*);

/* import: 'env' 'getValueObject' */
u32 w2c_env_getValueObject(struct w2c_env*, u32);

/* import: 'env' 'hook' */
u32 w2c_env_hook(struct w2c_env*, u32, u32);

/* import: 'env' 'logInfo' */
void w2c_env_logInfo(struct w2c_env*, u32);

/* import: 'env' 'moveArg' */
u32 w2c_env_moveArg(struct w2c_env*, u32);

/* import: 'env' 'toCString' */
void w2c_env_toCString(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'toCsStringWithLength' */
u32 w2c_env_toCsStringWithLength(struct w2c_env*, u32, u32);

/* import: 'env' 'unhook' */
u32 w2c_env_unhook(struct w2c_env*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_Module_memory(w2c_Module* instance);

/* export: 'onLoad' */
void w2c_Module_onLoad(w2c_Module*);

/* export: 'onUnload' */
void w2c_Module_onUnload(w2c_Module*);

/* export: 'onUiUpdate' */
void w2c_Module_onUiUpdate(w2c_Module*);

/* export: 'onFuseBoxUseNetworked' */
void w2c_Module_onFuseBoxUseNetworked(w2c_Module*);

/* export: 'onCreateRoom' */
void w2c_Module_onCreateRoom(w2c_Module*);

/* export: '_initialize' */
void w2c_Module_0x5Finitialize(w2c_Module*);

#ifdef __cplusplus
}
#endif

#endif  /* MODULE_H_GENERATED_ */
